### ISSUE TITLE
ValueError: invalid contig `1` 

### ISSUE THREAD

**Issue by VJ-Ulaganathan** [santiagosnchez/vcf2fasta#11]
**For certain *.vcf.gz files, I get the following error.**
This keeps popping up for a large majority of VCF files, I have tried so far.
Is there a clean-up step you would recommend? Thanks for your solution.

Total number of genes found: 16118
Traceback (most recent call last):
  File "new_vcf2fasta.py", line 515, in <module>
    main()
  File "new_vcf2fasta.py", line 139, in main
    sequences,varsites,codon_start,strand = getSequences(gff, gene, args.feat, args.blend, args.inframe, ref, vcf, ploidy, phased, samples, args.addref)
  File "new_vcf2fasta.py", line 206, in getSequences
    for rec in vcf.fetch(chrom, start, end):
  File "pysam/libcbcf.pyx", line 4403, in pysam.libcbcf.VariantFile.fetch
  File "pysam/libchtslib.pyx", line 685, in pysam.libchtslib.HTSFile.parse_region
ValueError: invalid contig `1`

I cannot figure what needs to corrected in the input *.vcf.gz file.
Shown below is first 100 lines for one such VCF.GZ file, that fails with the ValueError. 
Can you please point out what is wrong with it? Or a solution such as shell script to correct it.
How to correct it, so that I stop getting the "ValueError: invalid contig '1'" 

---------------------------------------------------------------------------------
##FILTER=<ID=PASS,Description="All filters passed">
##fileDate=20171120
##source=freeBayes v0.9.21-24-g840b412-dirty
##reference=/tmp/crunch-job-task-work/compute130.1/tmpdir/tmpguHQBc/stgc45620b5-8fdc-4785-8fcc-033b0f6c8463/hg19.fa
##phasing=none
##commandline="freebayes -f /tmp/crunch-job-task-work/compute130.1/tmpdir/tmpguHQBc/stgc45620b5-8fdc-4785-8fcc-033b0f6c8463/hg19.fa -4 /tmp/crunch-job-task-work/compute130.1/tmpdir/tmpguHQBc/stg6c0c27d0-e15c-4548-9cec-f42e443bc2db/55001703461631.chr16.bam"
##INFO=<ID=NS,Number=1,Type=Integer,Description="Number of samples with data">
##INFO=<ID=DP,Number=1,Type=Integer,Description="Total read depth at the locus">
##INFO=<ID=DPB,Number=1,Type=Float,Description="Total read depth per bp at the locus; bases in reads overlapping / bases in haplotype">
##INFO=<ID=AF,Number=A,Type=Float,Description="Estimated allele frequency in the range (0,1]">
##INFO=<ID=RO,Number=1,Type=Integer,Description="Reference allele observation count, with partial observations recorded fractionally">
##INFO=<ID=AO,Number=A,Type=Integer,Description="Alternate allele observations, with partial observations recorded fractionally">
##INFO=<ID=PRO,Number=1,Type=Float,Description="Reference allele observation count, with partial observations recorded fractionally">
##INFO=<ID=PAO,Number=A,Type=Float,Description="Alternate allele observations, with partial observations recorded fractionally">
##INFO=<ID=QR,Number=1,Type=Integer,Description="Reference allele quality sum in phred">
##INFO=<ID=QA,Number=A,Type=Integer,Description="Alternate allele quality sum in phred">
##INFO=<ID=PQR,Number=1,Type=Float,Description="Reference allele quality sum in phred for partial observations">
##INFO=<ID=PQA,Number=A,Type=Float,Description="Alternate allele quality sum in phred for partial observations">
##INFO=<ID=SRF,Number=1,Type=Integer,Description="Number of reference observations on the forward strand">
##INFO=<ID=SRR,Number=1,Type=Integer,Description="Number of reference observations on the reverse strand">
##INFO=<ID=SAF,Number=A,Type=Integer,Description="Number of alternate observations on the forward strand">
##INFO=<ID=SAR,Number=A,Type=Integer,Description="Number of alternate observations on the reverse strand">
##INFO=<ID=SRP,Number=1,Type=Float,Description="Strand balance probability for the reference allele: Phred-scaled upper-bounds estimate of the probability of observing the deviation between SRF and SRR given E(SRF/SRR) ~ 0.5, derived using Hoeffding's inequality">
##INFO=<ID=SAP,Number=A,Type=Float,Description="Strand balance probability for the alternate allele: Phred-scaled upper-bounds estimate of the probability of observing the deviation between SAF and SAR given E(SAF/SAR) ~ 0.5, derived using Hoeffding's inequality">
##INFO=<ID=AB,Number=A,Type=Float,Description="Allele balance at heterozygous sites: a number between 0 and 1 representing the ratio of reads showing the reference allele to all reads, considering only reads from individuals called as heterozygous">
##INFO=<ID=ABP,Number=A,Type=Float,Description="Allele balance probability at heterozygous sites: Phred-scaled upper-bounds estimate of the probability of observing the deviation between ABR and ABA given E(ABR/ABA) ~ 0.5, derived using Hoeffding's inequality">
##INFO=<ID=RUN,Number=A,Type=Integer,Description="Run length: the number of consecutive repeats of the alternate allele in the reference genome">
##INFO=<ID=RPP,Number=A,Type=Float,Description="Read Placement Probability: Phred-scaled upper-bounds estimate of the probability of observing the deviation between RPL and RPR given E(RPL/RPR) ~ 0.5, derived using Hoeffding's inequality">
##INFO=<ID=RPPR,Number=1,Type=Float,Description="Read Placement Probability for reference observations: Phred-scaled upper-bounds estimate of the probability of observing the deviation between RPL and RPR given E(RPL/RPR) ~ 0.5, derived using Hoeffding's inequality">
##INFO=<ID=RPL,Number=A,Type=Float,Description="Reads Placed Left: number of reads supporting the alternate balanced to the left (5') of the alternate allele">
##INFO=<ID=RPR,Number=A,Type=Float,Description="Reads Placed Right: number of reads supporting the alternate balanced to the right (3') of the alternate allele">
##INFO=<ID=EPP,Number=A,Type=Float,Description="End Placement Probability: Phred-scaled upper-bounds estimate of the probability of observing the deviation between EL and ER given E(EL/ER) ~ 0.5, derived using Hoeffding's inequality">
##INFO=<ID=EPPR,Number=1,Type=Float,Description="End Placement Probability for reference observations: Phred-scaled upper-bounds estimate of the probability of observing the deviation between EL and ER given E(EL/ER) ~ 0.5, derived using Hoeffding's inequality">
##INFO=<ID=DPRA,Number=A,Type=Float,Description="Alternate allele depth ratio.  Ratio between depth in samples with each called alternate allele and those without.">
##INFO=<ID=ODDS,Number=1,Type=Float,Description="The log odds ratio of the best genotype combination to the second-best.">
##INFO=<ID=GTI,Number=1,Type=Integer,Description="Number of genotyping iterations required to reach convergence or bailout.">
##INFO=<ID=TYPE,Number=A,Type=String,Description="The type of allele, either snp, mnp, ins, del, or complex.">
##INFO=<ID=CIGAR,Number=A,Type=String,Description="The extended CIGAR representation of each alternate allele, with the exception that '=' is replaced by 'M' to ease VCF parsing.  Note that INDEL alleles do not have the first matched base (which is provided by default, per the spec) referred to by the CIGAR.">
##INFO=<ID=NUMALT,Number=1,Type=Integer,Description="Number of unique non-reference alleles in called genotypes at this position.">
##INFO=<ID=MEANALT,Number=A,Type=Float,Description="Mean number of unique non-reference allele observations per sample with the corresponding alternate alleles.">
##INFO=<ID=LEN,Number=A,Type=Integer,Description="allele length">
##INFO=<ID=MQM,Number=A,Type=Float,Description="Mean mapping quality of observed alternate alleles">
##INFO=<ID=MQMR,Number=1,Type=Float,Description="Mean mapping quality of observed reference alleles">
##INFO=<ID=PAIRED,Number=A,Type=Float,Description="Proportion of observed alternate alleles which are supported by properly paired read fragments">
##INFO=<ID=PAIREDR,Number=1,Type=Float,Description="Proportion of observed reference alleles which are supported by properly paired read fragments">
##FORMAT=<ID=GL,Number=G,Type=Float,Description="Genotype Likelihood, log10-scaled likelihoods of the data given the called genotype for each possible genotype generated from the reference and alternate alleles given the sample ploidy">
##FORMAT=<ID=RO,Number=1,Type=Integer,Description="Reference allele observation count">
##FORMAT=<ID=QR,Number=1,Type=Integer,Description="Sum of quality of the reference observations">
##FORMAT=<ID=AO,Number=A,Type=Integer,Description="Alternate allele observation count">
##FORMAT=<ID=QA,Number=A,Type=Integer,Description="Sum of quality of the alternate observations">
##source=VarScan2
##INFO=<ID=ADP,Number=1,Type=Integer,Description="Average per-sample depth of bases with Phred score >= 15">
##INFO=<ID=WT,Number=1,Type=Integer,Description="Number of samples called reference (wild-type)">
##INFO=<ID=HET,Number=1,Type=Integer,Description="Number of samples called heterozygous-variant">
##INFO=<ID=HOM,Number=1,Type=Integer,Description="Number of samples called homozygous-variant">
##INFO=<ID=NC,Number=1,Type=Integer,Description="Number of samples not called">
##FILTER=<ID=str10,Description="Less than 10% or more than 90% of variant supporting reads on one strand">
##FILTER=<ID=indelError,Description="Likely artifact due to indel reads at this position">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Genotype Quality">
##FORMAT=<ID=SDP,Number=1,Type=Integer,Description="Raw Read Depth as reported by SAMtools">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Quality Read Depth of bases with Phred score >= 15">
##FORMAT=<ID=RD,Number=1,Type=Integer,Description="Depth of reference-supporting bases (reads1)">
##FORMAT=<ID=AD,Number=1,Type=Integer,Description="Depth of variant-supporting bases (reads2)">
##FORMAT=<ID=FREQ,Number=1,Type=String,Description="Variant allele frequency">
##FORMAT=<ID=PVAL,Number=1,Type=String,Description="P-value from Fisher's Exact Test">
##FORMAT=<ID=RBQ,Number=1,Type=Integer,Description="Average quality of reference-supporting bases (qual1)">
##FORMAT=<ID=ABQ,Number=1,Type=Integer,Description="Average quality of variant-supporting bases (qual2)">
##FORMAT=<ID=RDF,Number=1,Type=Integer,Description="Depth of reference-supporting bases on forward strand (reads1plus)">
##FORMAT=<ID=RDR,Number=1,Type=Integer,Description="Depth of reference-supporting bases on reverse strand (reads1minus)">
##FORMAT=<ID=ADF,Number=1,Type=Integer,Description="Depth of variant-supporting bases on forward strand (reads2plus)">
##FORMAT=<ID=ADR,Number=1,Type=Integer,Description="Depth of variant-supporting bases on reverse strand (reads2minus)">
##source_20171120.1=vcf-merge(r840) /tmp/crunch-job-task-work/compute130.1/tmpdir/tmpoK8jAf/stgec1aa75e-84af-4cdc-b742-2e4e5bdb4d2b/55001703461631.chr16.FB.vcf.gz /tmp/crunch-job-task-work/compute130.1/tmpdir/tmpoK8jAf/stga2413dd8-8031-42ea-9db8-a6823c1fb91a/55001703461631.chr16.VS.vcf.gz
##sourceFiles_20171120.1=0:/tmp/crunch-job-task-work/compute130.1/tmpdir/tmpoK8jAf/stgec1aa75e-84af-4cdc-b742-2e4e5bdb4d2b/55001703461631.chr16.FB.vcf.gz,1:/tmp/crunch-job-task-work/compute130.1/tmpdir/tmpoK8jAf/stga2413dd8-8031-42ea-9db8-a6823c1fb91a/55001703461631.chr16.VS.vcf.gz
##INFO=<ID=SF,Number=.,Type=String,Description="Source File (index to sourceFiles, f when filtered)">
##INFO=<ID=AC,Number=.,Type=Integer,Description="Allele count in genotypes">
##INFO=<ID=AN,Number=1,Type=Integer,Description="Total number of alleles in called genotypes">
##contig=<ID=chr16>
##contig=<ID=chr13>
##contig=<ID=chrY>
##contig=<ID=chr20>
##contig=<ID=chr17>
##contig=<ID=chr21>
##contig=<ID=chr4>
##contig=<ID=chr9>
##contig=<ID=chr6>
##contig=<ID=chr1>
##contig=<ID=chrM>
##contig=<ID=chr11>
##contig=<ID=chrX>
##contig=<ID=chr5>
##contig=<ID=chr7>
##contig=<ID=chr22>
##contig=<ID=chr14>
##contig=<ID=chr15>
##contig=<ID=chr3>
##contig=<ID=chr18>
##contig=<ID=chr8>
##contig=<ID=chr10>
##contig=<ID=chr12>
##contig=<ID=chr2>
##contig=<ID=chr19>
##bcftools_concatVersion=1.3.1+htslib-1.3.1
##bcftools_concatCommand=concat /keep/df56ae7c6366070a5f77230f70793e7c+158/55001703461631.chr16.FB.vcf.Merged.vcf.gz /keep/c7d769f71c702b516f78ba57842356ed+158/55001703461631.chr13.FB.vcf.Merged.vcf.gz /keep/ef1a23ee9e65fd48da2b44e9ea06222b+154/55001703461631.chrY.FB.vcf.Merged.vcf.gz /keep/bd5aba8ecabb83f9343118718f2e574c+158/55001703461631.chr20.FB.vcf.Merged.vcf.gz /keep/692e011aa8a678c14df8541727534fce+158/55001703461631.chr17.FB.vcf.Merged.vcf.gz /keep/9380e0769febed28e25f4c70ba30fe6f+158/55001703461631.chr21.FB.vcf.Merged.vcf.gz /keep/ce8bb01cea1ef0e8c64f12da2da4cfbc+157/55001703461631.chr4.FB.vcf.Merged.vcf.gz /keep/cc312a4e2240c01cf99f6f40c832fea7+156/55001703461631.chr9.FB.vcf.Merged.vcf.gz /keep/e0a0dba140a8e162b4351c3f79917494+157/55001703461631.chr6.FB.vcf.Merged.vcf.gz /keep/077aa25a4c2e74089048ee7007fd51dd+157/55001703461631.chr1.FB.vcf.Merged.vcf.gz /keep/6e61be8df2dc623e2c2cad98518c8167+148/55001703461631.chrM.FB.vcf.Merged.vcf.gz /keep/793911e12c60bbd72ef848eed87b72f6+158/55001703461631.chr11.FB.vcf.Merged.vcf.gz /keep/530066aa204fb172f8214d25337495b3+156/55001703461631.chrX.FB.vcf.Merged.vcf.gz /keep/84a18d367c1f3aaff571394303059c81+157/55001703461631.chr5.FB.vcf.Merged.vcf.gz /keep/d8dc819daae6af3d99432339a6e3be83+156/55001703461631.chr7.FB.vcf.Merged.vcf.gz /keep/984a43c19aa7804ed30fca46155a439b+158/55001703461631.chr22.FB.vcf.Merged.vcf.gz /keep/22058a7d2d97d99289baa7ff5c93254a+158/55001703461631.chr14.FB.vcf.Merged.vcf.gz /keep/0c0afde8e866086a891bd92e45a21194+158/55001703461631.chr15.FB.vcf.Merged.vcf.gz /keep/a0a72d8de841a3561ed1bcb6afe3aebd+157/55001703461631.chr3.FB.vcf.Merged.vcf.gz /keep/203131e4384bf3e0dcd1b1bbceb7a34a+158/55001703461631.chr18.FB.vcf.Merged.vcf.gz /keep/eb13b79d36546f1910cc7f7603f6eef6+156/55001703461631.chr8.FB.vcf.Merged.vcf.gz /keep/21f177414e164b058e9d2cabbfd7bfb6+158/55001703461631.chr10.FB.vcf.Merged.vcf.gz /keep/56f7bafa4f1555ed95b60a8dcffbde81+158/55001703461631.chr12.FB.vcf.Merged.vcf.gz /keep/054ee21656c2852fe48db875e41c7772+157/55001703461631.chr2.FB.vcf.Merged.vcf.gz /keep/ffa036480879b431391dc5ed61fbff42+158/55001703461631.chr19.FB.vcf.Merged.vcf.gz
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	unknown	Sample1
chr1	9999	.	N	G	.	PASS	AC=2;ADP=12;AN=2;HET=0;HOM=1;NC=0;SF=1;WT=0	GT:ADF:RD:ABQ:RDF:RBQ:ADR:DP:GQ:SDP:FREQ:PVAL:RDR:AD	.	1/1:0:0:29:0:0:10:12:52:12:83.33%:5.4125E-6:0:10
chr1	10000	.	N	A	.	PASS	AC=2;ADP=12;AN=2;HET=0;HOM=1;NC=0;SF=1;WT=0	GT:RD:ADF:ABQ:RDF:RBQ:GQ:PVAL:SDP:FREQ:DP:ADR:RDR:AD	.	1/1:0:0:27:0:0:64:3.698E-7:12:100%:12:12:0:12

**Comment by VJ-Ulaganathan** [comment]
I figured a solution. The issue lies in the alignment files.
