### ISSUE TITLE
run with error

### ISSUE THREAD

**Issue by zhouyanli11** [santiagosnchez/vcf2fasta#3]
$/home/zhouyanli/vcf2fasta/vcf2fasta.py --fasta ../Oryza_barthii.O.barthii_v1.dna.normalize.toplevel.fa --vcf Barthii_94sample.vcf.gz --gff Obarthi.stringtie.gff3 --feat CDS
When I was running this commond, it did not work like this:
Reading VCF file [Obarthi.stringtie.gff3] ... Traceback (most recent call last):
  File "/home/zhouyanli/vcf2fasta/vcf2fasta.py", line 481, in <module>
    main()
  File "/home/zhouyanli/vcf2fasta/vcf2fasta.py", line 66, in main
    gff = filterFeatureInGFF(ReadGFF(args.gff), args.feat)
  File "/home/zhouyanli/vcf2fasta/vcf2fasta.py", line 413, in ReadGFF
    geneNames = getGeneNames(file)
  File "/home/zhouyanli/vcf2fasta/vcf2fasta.py", line 391, in getGeneNames
    last = processGeneName(fields[8])
IndexError: list index out of range

**Comment by santiagosnchez** [comment]
Remove all comments from the GFF file for now. I'll add a comment filtering step.

**Comment by santiagosnchez** [comment]
> Remove all comments from the GFF file for now. I'll add a comment filtering step.

Added a comment filtering lines to the GFF read step: https://github.com/santiagosnchez/vcf2fasta/blob/b5cbb5b1e8af2c9d56e85ca936ebafa020ec4968/vcf2fasta.py#L429

**Comment by zhouyanli11** [comment]
hello,
Thanks very much for your troubleshooting.
I also get a problem of "Reading VCF file [Osjap10g14600.1.gff] ... done
Reading VCF file [japonica.combine.vcf.gz] ... done
Reading VCF file [all.chrs.con.fa] ... done
Ploidy is: 2
No phased genotypes found on first variant. Treating as "unphased"
Concatenating all [ CDS ]
Setting output directory to: vcf2fasta_CDS
vcf2fasta_CDS exists. Do you want to proceed? [y|n]: y
Total number of genes found: 1
Traceback (most recent call last):
  File "/home/zhouyanli/vcf2fasta/vcf2fasta.py", line 481, in <module>
    main()
  File "/home/zhouyanli/vcf2fasta/vcf2fasta.py", line 119, in main
    sequences = getSequences(gff, gene, args.feat, args.blend, ref, vcf, ploidy, phased, samples)
  File "/home/zhouyanli/vcf2fasta/vcf2fasta.py", line 216, in getSequences
    alleles,max_len = getAlleles(rec, ploidy)
  File "/home/zhouyanli/vcf2fasta/vcf2fasta.py", line 264, in getAlleles
    max_len = max([ len(i) for i in segregating if i is not None ])
ValueError: max() arg is an empty sequence"

**Comment by matthewglasenapp** [comment]
I am running into a similar issue:

Reading GFF file [test.gff] ... done
Reading VCF file [/hb/scratch/mglasena/phylonet_hmm/phylonet_hmm_variant_sites_vcf/3bp_filtered_genotype_calls_pf.g.vcf.gz] ... done
Reading FASTA reference file [/hb/home/mglasena/dissertation/data/purpuratus_reference/GCF_000002235.5_Spur_5.0_genomic.fna] ... done
Ploidy is: 2
No phased genotypes found on first variant. Treating as "unphased"
Writing all [ gene ] separately
Setting output directory to: vcf2fasta_gene
Total number of genes found: 1
Found all genes with single records. Treating as --blend
Traceback (most recent call last):
  File "/hb/home/mglasena/software/test/vcf2fasta/vcf2fasta.py", line 515, in <module>
    main()
  File "/hb/home/mglasena/software/test/vcf2fasta/vcf2fasta.py", line 139, in main
    sequences,varsites,codon_start,strand = getSequences(gff, gene, args.feat, args.blend, args.inframe, ref, vcf, ploidy, phased, samples, args.addref)
  File "/hb/home/mglasena/software/test/vcf2fasta/vcf2fasta.py", line 212, in getSequences
    alleles,max_len = getAlleles(rec, ploidy, phased, addref)
  File "/hb/home/mglasena/software/test/vcf2fasta/vcf2fasta.py", line 250, in getAlleles
    max_len = max([ len(i) for i in segregating if i is not None ])
ValueError: max() arg is an empty sequence
