### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by khyati-sb** [santiagosnchez/vcf2fasta#5]
Hi

I am trying to use your script VCF2fasta.py, and as per the requirements I have used indexed and compressed files for reference genome as well as vcf file. My vcf file is multi-sample file. Also, Gff file used here is from NCBI Refseq database. I also removed comments from gif file as described in Issue3 Yet, somehow I am getting the following error while running:

`python /home/bcgrc/bin/vcf2fasta/vcf2fasta.py -f Ref_70-15.fa -g Ref_70-15.gff -e gene -v all_snps.vcf.gz `
>Reading GFF file [Ref_70-15.gff] ... Traceback (most recent call last):
  File "/home/bcgrc/bin/vcf2fasta/vcf2fasta.py", line 470, in <module>
    main()
  File "/home/bcgrc/bin/vcf2fasta/vcf2fasta.py", line 78, in main
    gff = filterFeatureInGFF(ReadGFF(args.gff), args.feat)
  File "/home/bcgrc/bin/vcf2fasta/vcf2fasta.py", line 405, in ReadGFF
    geneNames = getGeneNames(file)
  File "/home/bcgrc/bin/vcf2fasta/vcf2fasta.py", line 378, in getGeneNames
    last = processGeneName(fields[8])
IndexError: list index out of range

Also, I am trying to convert vcf to Fasta for all the region, Not just restricted to gene or CDS.
Your help is much appreciated.

**Comment by vguerracanedo** [comment]
I have the same problem. I wonder if a solution to this problem has been found?
Thank you

**Comment by VJ-Ulaganathan** [comment]
Check if there are mismatches among reference.fa, the gff file & your input vcf.gz files in terms of Chromosome position entries.
In both the files, there should be consistency in the nomenclature of CHR position entries and gene id nomenclature.
