### ISSUE TITLE
KeyError: 'ID'

### ISSUE THREAD

**Issue by alexpmagalhaes** [santiagosnchez/vcf2fasta#6]
I'm getting this error when trying to call from variant sequences from VCF.

```
Reading GFF file [/Users/magalhae/Desktop/IDRClinVar/VEP/FASTA/Homo_sapiens.GRCh38.104.gff3] ... Traceback (most recent call last):
  File "/Users/magalhae/Desktop/IDRClinVar/VEP/FASTA/vcf2fasta.py", line 470, in <module>
    main()
  File "/Users/magalhae/Desktop/IDRClinVar/VEP/FASTA/vcf2fasta.py", line 78, in main
    gff = filterFeatureInGFF(ReadGFF(args.gff), args.feat)
  File "/Users/magalhae/Desktop/IDRClinVar/VEP/FASTA/vcf2fasta.py", line 421, in ReadGFF
    gff[last['ID']][fields[2]].append(fields)
KeyError: 'ID'
```

maybe something to do with my gff file? bellow a sample of the file

```
1	havana	mRNA	65419	71585	.	+	.	ID=ENST00000641515;Parent=ENSG00000186092;Name=OR4F5-201;biotype=protein_coding;tag=basic;transcript_id=ENST00000641515;version=2
1	havana	exon	65419	65433	.	+	.	Parent=ENST00000641515;Name=ENSE00003812156;constitutive=1;ensembl_end_phase=-1;ensembl_phase=-1;exon_id=ENSE00003812156;rank=1;version=1
1	havana	five_prime_UTR	65419	65433	.	+	.	Parent=ENST00000641515
1	havana	five_prime_UTR	65520	65564	.	+	.	Parent=ENST00000641515
1	havana	exon	65520	65573	.	+	.	Parent=ENST00000641515;Name=ENSE00003813641;constitutive=1;ensembl_end_phase=0;ensembl_phase=-1;exon_id=ENSE00003813641;rank=2;version=1
1	havana	CDS	65565	65573	.	+	0	ID=ENSP00000493376;Parent=ENST00000641515;protein_id=ENSP00000493376
1	havana	CDS	69037	70008	.	+	0	ID=ENSP00000493376;Parent=ENST00000641515;protein_id=ENSP00000493376
1	havana	exon	69037	71585	.	+	.	Parent=ENST00000641515;Name=ENSE00003813949;constitutive=1;ensembl_end_phase=-1;ensembl_phase=0;exon_id=ENSE00003813949;rank=3;version=1
1	havana	three_prime_UTR	70009	71585	.	+	.	Parent=ENST00000641515
```

Can you help?

**Comment by VJ-Ulaganathan** [comment]
Try using a GTF file instead of GFF file. In my case, the KeyError: "ID" issue was solved.

**Comment by kmosi0** [comment]
I get this error too when I use the gff3 file. it was caused by a mistake in  line 381 of vcf2fasta.py
          if format == "GFF":
this "GFF" should lower case, change to  "if format == "gff":" this problem will be solved
